lf

diff --git a/lf/.config/lf/scope b/lf/.config/lf/scope
--- a/lf/.config/lf/scope
+++ b/lf/.config/lf/scope
@@ -1,58 +1,158 @@
 #!/bin/bash
 
-set -C -f -u
-#IFS=$'\n'
-IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"
+# set -C -f -u
+# #IFS=$'\n'
+# IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"
+#
+# # ANSI color codes are supported.
+# # STDIN is disabled, so interactive scripts won't work properly
+#
+# # This script is considered a configuration file and must be updated manually.
+#
+# # Meanings of exit codes:
+# # code | meaning    | action of ranger
+# # -----+------------+-------------------------------------------
+# # 0    | success    | Display stdout as preview
+# # 1    | no preview | Display no preview at all
+# # 2    | plain text | Display the plain content of the file
+#
+# # Script arguments
+# FILE_PATH="${1}"         # Full path of the highlighted file
+# HEIGHT="${2}"
+#
+# #FILE_EXTENSION="${FILE_PATH##*.}"
+# #FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')
+#
+# # Settings
+# HIGHLIGHT_SIZE_MAX=262143  # 256KiB
+# HIGHLIGHT_TABWIDTH=8
+# HIGHLIGHT_STYLE='pablo'
+#
+#
+# handle_mime() {
+#     local mimetype="${1}"
+#     case "${mimetype}" in
+# 	text/html) w3m -dump "${FILE_PATH}" ;;
+# 	text/troff) man ./ "${FILE_PATH}" | col -b ;;
+# 	text/* | */xml)
+#             if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
+#                 exit 2
+#             fi
+#             if [ "$( tput colors )" -ge 256 ]; then
+#                 local highlight_format='xterm256'
+#             else
+#                 local highlight_format='ansi'
+#             fi
+#             highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
+#                 --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
+# 	application/zip) atool --list -- "${FILE_PATH}" ;;
+#         image/*) chafa --fill=block --symbols=block -c 256 -s 80x"${HEIGHT}" "${FILE_PATH}" || exit 1;;
+#         video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
+#         */pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
+#         *opendocument*) odt2txt "${FILE_PATH}" ;;
+#     esac
+# }
+#
+# MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
+# handle_mime "${MIMETYPE}"
+# exit 1
 
-# ANSI color codes are supported.
-# STDIN is disabled, so interactive scripts won't work properly
-
-# This script is considered a configuration file and must be updated manually.
-
-# Meanings of exit codes:
-# code | meaning    | action of ranger
-# -----+------------+-------------------------------------------
-# 0    | success    | Display stdout as preview
-# 1    | no preview | Display no preview at all
-# 2    | plain text | Display the plain content of the file
-
-# Script arguments
-FILE_PATH="${1}"         # Full path of the highlighted file
-HEIGHT="${2}"
-
-#FILE_EXTENSION="${FILE_PATH##*.}"
-#FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')
-
-# Settings
-HIGHLIGHT_SIZE_MAX=262143  # 256KiB
-HIGHLIGHT_TABWIDTH=8
-HIGHLIGHT_STYLE='pablo'
 
 
-handle_mime() {
-    local mimetype="${1}"
-    case "${mimetype}" in
-	text/html) w3m -dump "${FILE_PATH}" ;;
-	text/troff) man ./ "${FILE_PATH}" | col -b ;;
-	text/* | */xml)
-            if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
-                exit 2
-            fi
-            if [ "$( tput colors )" -ge 256 ]; then
-                local highlight_format='xterm256'
-            else
-                local highlight_format='ansi'
-            fi
-            highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
-                --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
-	application/zip) atool --list -- "${FILE_PATH}" ;;
-        image/*) chafa --fill=block --symbols=block -c 256 -s 80x"${HEIGHT}" "${FILE_PATH}" || exit 1;;
-        video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
-        */pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
-        *opendocument*) odt2txt "${FILE_PATH}" ;;
-    esac
+
+
+
+
+
+
+
+
+
+#!/bin/sh
+
+image() {
+	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
+		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
+		exit 1
+	else
+		chafa "$1" -s "$4x"
+	fi
 }
 
-MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
-handle_mime "${MIMETYPE}"
-exit 1
+batorcat() {
+	file="$1"
+	shift
+	if command -v bat > /dev/null 2>&1
+	then
+		bat --color=always --style=plain --pager=never "$file" "$@"
+	else
+		cat "$file"
+	fi
+}
+
+CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
+
+case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
+	*.tgz|*.tar.gz) tar tzf "$1" ;;
+	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
+	*.tar.txz|*.txz) xz --list "$1" ;;
+	*.tar) tar tf "$1" ;;
+	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
+	*.rar) unrar l "$1" ;;
+  *.md) glow -s dark "$1" ;;
+	*.7z) 7z l "$1" ;;
+	*.[1-8]) man "$1" | col -b ;;
+	*.o) nm "$1";;
+	*.torrent) transmission-show "$1" ;;
+	*.iso) iso-info --no-header -l "$1" ;;
+	*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
+	*.doc) catdoc "$1" ;;
+	*.docx) docx2txt "$1" - ;;
+  *.xml|*.html) w3m -dump "$1";;
+	*.xls|*.xlsx)
+		ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
+		;;
+	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
+		exiftool "$1"
+		;;
+	*.pdf)
+		[ ! -f "${CACHE}.jpg" ] && \
+			pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
+		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+		;;
+	*.epub)
+		[ ! -f "$CACHE" ] && \
+			epub-thumbnailer "$1" "$CACHE" 1024
+		image "$CACHE" "$2" "$3" "$4" "$5"
+		;;
+	*.cbz|*.cbr|*.cbt)
+		[ ! -f "$CACHE" ] && \
+			comicthumb "$1" "$CACHE" 1024
+		image "$CACHE" "$2" "$3" "$4" "$5"
+		;;
+	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
+		[ ! -f "${CACHE}.jpg" ] && \
+			ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
+		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+		;;
+	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif)
+		image "$1" "$2" "$3" "$4" "$5"
+		;;
+  *.svg)
+    [ ! -f "${CACHE}.jpg" ] && \
+      convert "$1" "${CACHE}.jpg"
+    image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+    ;;
+	*.ino)
+		batorcat --language=cpp "$1"
+		;;
+	*)
+		batorcat "$1"
+		;;
+esac
+exit 0
+
+
+
+
+
