add

diff --git a/bin/.local/bin/mygh b/bin/.local/bin/mygh
--- a/bin/.local/bin/mygh
+++ b/bin/.local/bin/mygh
@@ -33,48 +33,49 @@ printf "${RESET}%s\n"
 printf "$GREEN%s"
 read -r -p "Please Enter Num 1、2、3、4、5、6 or 7 for github-cli: " -e inputNum
 case ${inputNum} in
-1)
-    cd "$HOME/github_upload" || exit
-    echo -e "${RED}"
-    read -r -p "Enter the name of the repository you want to create: " -e Repo_Name
-    gh repo create "$Repo_Name" --clone --private
-    ;;
-2)
-    cd "$HOME/github_upload" || exit
-    echo -e "${RED}"
-    read -r -p "Enter the name of the repository you want to clone: " -e Repo_Name
-    gh repo clone "$Repo_Name"
-    ;;
-3)
-    echo -e "${RED}"
-    read -r -p "Enter the name of the repository you want to delete: " -e Repo_Name
-    gh repo delete lcdse7en/"$Repo_Name"
-    ;;
-4)
-    echo -e "${RED}"
-    read -r -p "Enter the name of the github you want to fork: " -e Github_Name
-    read -r -p "Enter the name of the repository you want to fork:" -e Repo_Name
-    gh repo fork "$Github_Name"/"$Repo_Name"
-    ;;
-5)
-    echo -e "${RED}"
-    read -r -p "Enter the new name of the repository you want to rename: " -e new_Name
-    read -r -p "Enter the old name of the repository you want to rename: " -e old_Name
-    gh repo rename "$new_Name" --repo lcdse7en/"$old_Name" --yes
-    ;;
-6)
-    echo -e "${RED}"
-    echo "Now, Show all private repo for you!"
-    gh repo list --visibility private
-    ;;
-7)
-    echo -e "${RED}"
-    echo -e "Now, Show all public repo for you!"
-    gh repo list --visibility public
-    ;;
-*)
-    printf "\n$BLUE%s$RESET\n" "Enter num error, Please enter again!"
-    ;;
+    1)
+        cd "$HOME/github_upload" || exit
+        echo -e "${RED}"
+        read -r -p "Enter the name of the repository you want to create: " -e Repo_Name
+        gh repo create "$Repo_Name" --clone --private
+        ;;
+    2)
+        cd "$HOME/github_upload" || exit
+        echo -e "${RED}"
+        read -r -p "Enter the name of the repository you want to clone: " -e Repo_Name
+        gh repo clone "$Repo_Name"
+        ;;
+    3)
+        echo -e "${RED}"
+        read -r -p "Enter the name of the repository you want to delete: " -e Repo_Name
+        gh repo delete "$Repo_Name" --yes
+        # gh auth refresh -s $Repo_Name
+        ;;
+    4)
+        echo -e "${RED}"
+        read -r -p "Enter the name of the github you want to fork: " -e Github_Name
+        read -r -p "Enter the name of the repository you want to fork:" -e Repo_Name
+        gh repo fork "$Github_Name"/"$Repo_Name"
+        ;;
+    5)
+        echo -e "${RED}"
+        read -r -p "Enter the new name of the repository you want to rename: " -e new_Name
+        read -r -p "Enter the old name of the repository you want to rename: " -e old_Name
+        gh repo rename "$new_Name" --repo "$old_Name" --yes
+        ;;
+    6)
+        echo -e "${RED}"
+        echo "Now, Show all private repo for you!"
+        gh repo list --visibility private
+        ;;
+    7)
+        echo -e "${RED}"
+        echo -e "Now, Show all public repo for you!"
+        gh repo list --visibility public
+        ;;
+    *)
+        printf "\n$BLUE%s$RESET\n" "Enter num error, Please enter again!"
+        ;;
 esac
 
 exit 0
